# -*- coding: utf-8 -*-import foursquareimport pymongofrom pymongo import Connectionimport sysimport urllib2 import jsonmConn = Connection("217.199.220.182")mGP = mConn.googleplaces.places_testdef getVenue(id):	key = "AIzaSyBeaQz_vzwERgPQZDncZYNhyAkYMG1JJY4"		url= "https://maps.googleapis.com/maps/api/place/details/json?reference=%s&sensor=false&language=ru&key=%s" % (id, key)	res =  json.loads(urllib2.urlopen(url).read())	return resfor iter in mGP.find():	try:		gpId = iter['reference']		rec = getVenue(gpId)['result'];		for k,v in rec.items():			iter[k]=v		mGP.save(iter)	except Exception, e:		print "Error: "+str(e)		sys.stdout.flush() 			